apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  demo-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  source:
    path: "application/resources"
    repoURL: https://github.com/tiagat/poc-ingress-solutions
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
