apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "6.13.1"
    helm:
      parameters:
        - name: provider
          value: aws
        - name: aws.credentials.secretName
          value: aws-credentials
        - name: aws.region
          value: us-east-1
      values: |
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        domainFilters: [tiagat.dev,]
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
