apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-service
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: demo.sandbox.tiagat.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-service
            port:
              number: 80
