apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-service
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: ingress-nginx
  rules:
    - host: nginx.local.tiagat.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-service
                port: 
                  number: 80
