apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  istio-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: istio-system
    name: in-cluster
  source:
    chart: istio-base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.20.2
    helm:
      parameters:
        - name: defaultRevision
          value: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
