apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librespeed
  template:
    metadata:
      labels:
        app: librespeed
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: librespeed
          image: lscr.io/linuxserver/librespeed:latest
          resources:
            requests:
              memory: 256Mi
              cpu: "1"
            limits:
              memory: 256Mi
              cpu: "500m"
